/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6575_NP. Copyright MediaTek Inc. (C) 2013.
 * Tue Dec 01 23:24:17 2015
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_HF_MIC_CHANNEL     1
#define AUXADC_TEMPERATURE_CHANNEL     3


#endif //_CUST_AUXADC_TOOL_H


